name: sprout
description: "Grow your financial future."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.3.0
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  http: ^1.4.0
  flutter_secure_storage: ^10.0.0
  provider: ^6.0.5
  uuid: ^4.5.1
  event_bus: ^2.0.1
  fl_chart: ^1.1.1
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  cupertino_icons: ^1.0.8
  get_it: ^9.2.0
  collection: ^1.19.1
  flutter_launcher_icons: ^0.14.4
  logger: ^2.6.1
  cached_network_image: ^3.4.1
  go_router: ^17.0.1
  app_links: ^7.0.0
  jwt_decoder: ^2.0.1
  firebase_messaging: ^16.1.1
  firebase_core: ^4.4.0
  flutter_local_notifications: ^20.0.0
  local_auth: ^3.0.0
  device_info_plus: ^12.3.0
  flutter_web_auth_2: ^5.0.1
  gpt_markdown: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/icon/
    - assets/login/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/color.png"
  min_sdk_android: 21
  adaptive_icon_background: "#141a1f"
  adaptive_icon_foreground_inset: 24
  adaptive_icon_foreground: "assets/icon/color.png"
  # We can't use this because we want to use an SVG as they render better on web
  # web:
  #   generate: true
  #   image_path: "assets/icon/favicon-bg-mask.svg"
  #   background_color: "#141a1f"
  #   theme_color: "#116383"
