site_name: Sprout
site_url: https://sprout.croudebush.net
repo_name: cameronroudebush/sprout
repo_url: https://github.com/cameronroudebush/sprout
theme:
  name: material
  logo: assets/favicon-bg.svg
  favicon: assets/favicon-bg.svg
  custom_dir: docs/overrides/
  features:
    - header.autohide
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.expand
    - navigation.footer
  palette:
    - scheme: slate
      primary: custom
      accent: custom
extra_css:
  - stylesheets/extra.css
  - stylesheets/custom-html.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cameronroudebush/sprout
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/croudebush/sprout
  generator: false
  analytics:
    provider: custom
    property: foobar
plugins:
  - search
  - social:
      cards: true
      cards_layout_options:
        background_color: "#1d2127"
        color: "#FFFFFF"
  - swagger-ui-tag:
      extra_css: [stylesheets/swagger.css]
      tryItOutEnabled: false
      supportedSubmitMethods: []
      filter: true
nav:
  - Home: index.md
  - Screenshots:
      - Desktop: images/desktop/README.md
      - Mobile: images/mobile/README.md
  - Getting Started:
      - Overview: getting-started/index.md
      - Installation: getting-started/installation.md
      - Configuration:
          - Overview: getting-started/configuration.md
          - Authentication: getting-started/auth.md
          - Notification: getting-started/notification.md
          - AI Integration: getting-started/llm.md
      - Providers: getting-started/providers.md
      - Accessing Sprout: getting-started/access.md
      - Backups: getting-started/backups.md
  - Developer:
      - Overview: developer/index.md
      - Configuration: developer/configuration.md
      - Known Issues: developer/known-issues.md
      - API Docs: developer/api.md
  - What's Next?: planned-features.md
  - Privacy Policy: privacy-policy.md
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
hooks:
  - docs/hooks/copyright_hook.py
exclude_docs: |
  *.xcf
